name: XcodeGenSample
options:
  deploymentTarget:
    iOS:  "12.0"
  postGenCommand: bundle exec pod install
configs:
  Develop: debug
  ProdDebug: debug
  ProdRelease: release
configFiles:
  Develop: Configurations/Debug.xcconfig
  ProdDebug: Configurations/Debug.xcconfig
  ProdRelease: Configurations/Release.xcconfig
settings:
  configs:
    Develop:
      GCC_PREPROCESSOR_DEFINITIONS: DEVELOP=1 $(inherited)
      OTHER_SWIFT_FLAGS: -D DEVELOP
schemes:
  Sample-Develop:
    build:
      targets:
        XcodeGenSample: all
        XcodeGenSampleTests: [test]
        XcodeGenSampleCoreTests: [test]
    run:
      config: Develop
    test:
      config: Develop
    profile: 
      config: Develop
    analyze:
      config: Develop
    archive: 
      config: Develop
  Sample-Prod:
    build:
      targets:
        XcodeGenSample: all
        XcodeGenSampleTests: [test]
        XcodeGenSampleCoreTests: [test]
    run:
      config: ProdDebug
    test:
      config: ProdDebug
    profile: 
      config: ProdRelease
    analyze:
      config: ProdDebug
    archive: 
      config: ProdRelease
targets:
  XcodeGenSample:
    type: application
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1000000
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.XcodeGenSample${BUNDLE_ID_SUFFIX}
      configs:
        Develop:
          BUNDLE_ID_SUFFIX: .develop
    sources:
      - path: XcodeGenSample
      - path: XcodeGenSample/DI/NeedleGenerated.swift
        optional: true
      - path: XcodeGenSample/Resources/R.generated.swift
        optional: true
    info:
      path: XcodeGenSample/Resources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchStoryboardName: LaunchScreen
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]      
    dependencies:
      - target: XcodeGenSampleCore
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
    preBuildScripts:
      - name: Run R.swift
        path: /bin/sh
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/XcodeGenSample/Resources/R.generated.swift
        script: $PODS_ROOT/R.swift/rswift generate $SRCROOT/XcodeGenSample/Resources/R.generated.swift
      - name: Run needle
        path: /bin/sh
        outputFiles:
          - $SRCROOT/XcodeGenSample/DI/NeedleGenerated.swift
        script: export SOURCEKIT_LOGGING=0 && Carthage/Checkouts/needle/Generator/bin/needle generate XcodeGenSample/DI/NeedleGenerated.swift XcodeGenSample/ XcodeGenSampleCore/DI/CoreComponent.swift        
    testTargets:
      - name: XcodeGenSampleTests
  XcodeGenSampleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: XcodeGenSampleTests  
    dependencies:
      - target: XcodeGenSample
      - carthage: Nimble
      - carthage: Cuckoo
      - carthage: RxTest
      - carthage: RxBlocking
  XcodeGenSampleCore:
    type: framework
    platform: iOS    
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.XcodeGenSampleCore
    info:
      path: XcodeGenSampleCore/Resources/Info.plist
    sources:
      - path: XcodeGenSampleCore
    dependencies:
      - carthage: RxSwift
  XcodeGenSampleCoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: XcodeGenSampleCoreTests  
    dependencies:
      - target: XcodeGenSampleCore
      - carthage: Nimble
      - carthage: Cuckoo
      - carthage: RxTest
      - carthage: RxBlocking      